### PR TITLE
Delete start.sh

### PR DESCRIPTION
**Pull request by wujunze**
remove start.sh     please use  orange command

### CODE REVIEW

**Comment by sumory** [comment]
LGTM

**Comment by wujunze** [comment]
@sumory  need approving  
image

**Comment by sumory** [comment]
master should not be merged by this way. 
all development must be done in another separate branch before merged into master.

**Comment by zhjwpku** [comment]
not sure about this, I think someone might be using the script heavily, maybe redundant is a good thing？

**Comment by sumory** [comment]
@zhjwpku scripts such as `start.sh` were designed for usages without `installation`. according to this point, it's better to keep it as before.

**Comment by zhjwpku** [comment]
@wujunze I think we should just close this PR according to the comments?

**Pull request closed without merging**
