### PR TITLE
[plug] dynamic ssl support

### PR DESCRIPTION
**Pull request by noname007**
now everyone can config cert and pkey at the dashboard

if you just have one machine  at the nginx.conf  del the below confige to del the dependency of redis:

```
ssl_session_fetch_by_lua_file *
ssl_session_store_by_lua_file *
```

if you are just using the TLS session tickets  you can ignore above .

deps: 

- lua-resty-redis, if you have to share the ssl session on multi sever
- shard_dict, must config , cache the cert and pkey data 
- [openssl patch](https://github.com/openresty/openresty/blob/master/patches/openssl-1.0.2h-sess_set_get_cb_yield.patch),   if you have to share the ssl session on multi sever  , more detail read the [doc](https://github.com/openresty/lua-nginx-module#ssl_session_fetch_by_lua_block) , if you lazy to do that by yourself ,you can refer [my makefile](https://github.com/noname007/script/blob/master/systemtap/Makefile#L178-L195) to install the openresty 1.11.2.2 and openssl 1.0.2k with the patch to the path `${home}/sofeware/openrestydd/ ` by run `make openresty` after download that makefile

### CODE REVIEW

**Comment by noname007** [comment]
文档 ：
https://github.com/thisverygoodhhhh/orange/wiki/dynamicssl

**Comment by noname007** [comment]
#137

**Comment by wujunze** [comment]
LGTM

**Comment by wujunze** [comment]
这个咱们讨论一下  要不要默认加进来  或者是作为一个插件

**Pull request closed without merging**
