### PR TITLE
feat: add websocket support to the proxy server

### PR DESCRIPTION
**Pull request by noname007**
proxy the websocket and http protocol at the same time

### CODE REVIEW

**Comment by noname007** [comment]
main refer: 

http://nginx.org/en/docs/http/websocket.html

**Comment by sumory** [comment]
maybe this feature should not be enabled by default.

**Comment by wujunze** [comment]
I think it would be better to use this as a plugin

**Comment by sumory** [comment]
yes! Orange should keep a simple & clean & stable core. 
it's better to integrate extensions with plugins.

**Comment by noname007** [comment]
充分使用我们所能使用的工具，实现简洁，尽量开箱既用，不破坏前向兼容。这或许更重要


午夜 <notifications@github.com> 于 2019年3月14日周四 13:48写道：

**Pull request merged**
